# These tasks will focus on software engineering in ***Python***, ***pandas***, ***data manipulation*** and ***testing***. The challenge will be solved in a pair programming modality where you will be the driver (i.e. the person coding) and the interviewer will be the navigator (i.e. the person helping you code).

## Pandas

In [23]:
import pandas as pd
import numpy as np
import logging

In [26]:
logging.basicConfig(
    filename='main.ipynb.log', 
    level=logging.INFO, 
    format="%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)")
logger = logging.getLogger(__name__)

In [34]:
filename = "../data/comic_books_10000_dataset.csv"

In [35]:
comic_book_df = pd.read_csv(filename)

In [5]:
comic_book_df.head()

,comic_id,Title,Writer,Artist,Studio/Publisher,Release Year,Format,Theme (Color Style),Genre,Country of Origin,Page Count,Rating (out of 10),Status,Language,Age Rating,Awards,Volume Count
0,CMC-00001,Tiger of Zero,Gintoki Sakata,Gintoki Sakata,Shogakukan (Viz Media),2001,Tankobon,Full Color (Special Edition),Shoujo / Romance,Japan,890,8.0,Ongoing,Japanese,Mature,NaN,13
1,CMC-00002,Twisted Claw,Fumi Takahashi,Mika Sasaki,Shogakukan (Viz Media),2015,Tankobon,Black & White,Action / Historical,Japan,2850,8.3,Completed,Japanese,Mature,NaN,12
2,CMC-00003,Jean Grey: Rebirth,Chip Zdarsky,Bendis,Marvel Comics,2016,Graphic Novel,Full Color,Superhero / Thriller,USA,350,7.8,Ongoing,English,Teen+,Japan Media Arts Award Winner,13
3,CMC-00004,Abyss Destiny,Yuna Yamaguchi,Yuna Yamaguchi,Kodansha (Kodansha USA),2014,Manga Volume,Black & White,Slice of Life / Drama,Japan,592,8.7,Cancelled,Japanese,Teen+,Eisner Award Nominee,13
4,CMC-00005,After Smoke,Shannon Watters,Warren Ellis,Kodansha Comics,2005,OGN,Black & White,Romance / Drama,USA,2465,7.0,Ongoing,English,Mature,NaN,4

In [15]:
comic_book_df.loc[comic_book_df.isna().any(axis=1)]

,comic_id,Title,Writer,Artist,Studio/Publisher,Release Year,Format,Theme (Color Style),Genre,Country of Origin,Page Count,Rating (out of 10),Status,Language,Age Rating,Awards,Volume Count
0,CMC-00001,Tiger of Zero,Gintoki Sakata,Gintoki Sakata,Shogakukan (Viz Media),2001,Tankobon,Full Color (Special Edition),Shoujo / Romance,Japan,890,8.0,Ongoing,Japanese,Mature,NaN,13
1,CMC-00002,Twisted Claw,Fumi Takahashi,Mika Sasaki,Shogakukan (Viz Media),2015,Tankobon,Black & White,Action / Historical,Japan,2850,8.3,Completed,Japanese,Mature,NaN,12
4,CMC-00005,After Smoke,Shannon Watters,Warren Ellis,Kodansha Comics,2005,OGN,Black & White,Romance / Drama,USA,2465,7.0,Ongoing,English,Mature,NaN,4
6,CMC-00007,Ancient X,Kazushi Hagiwara,Vegeta style,Square Enix (Yen Press),2017,Manga Volume,Black & White,Romance / Comedy,Japan,4186,8.0,Ongoing,Japanese,Mature,NaN,43
8,CMC-00009,Day Fang,Akira Toriyama,Luffy style,Kodansha (Kodansha USA),2023,Single Issue / Tankobon,Black & White,Historical / Drama,Japan,1455,8.5,Completed,Japanese,Teen+,NaN,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,CMC-09996,Forsaken Reincarnation,Kai Yoshida,Kai Yoshida,Leed-sha,2019,Single Issue / Tankobon,Black & White,Psychological / Thriller,Japan,4143,7.9,Ongoing,Japanese,Young Adult,NaN,15
9996,CMC-09997,Lion Memory,Daisuke Imai,Mitsuru Adachi,Ichijinsha,2019,Manga Volume,Black & White,School / Romance,Japan,2987,8.3,Hiatus,Japanese,Teen+,NaN,45
9997,CMC-09998,Legendary F-Ranked Void System,Nam Hyun-jun,Go Chan,Kakao Webtoon,2017,Digital Webtoon,Full Color / Limited Palette,Reincarnation / Fantasy,South Korea,1548,6.9,Ongoing,Korean,Mature,NaN,13
9998,CMC-09999,The Lost Gold,Noelle Stevenson,Faith Erin Hicks,Drawn & Quarterly,2023,Omnibus,Black & White,Adventure / Comedy,New Zealand,1758,7.2,Completed,English,Mature,NaN,8
9999,CMC-10000,Hero Tower,Jung Ha,Choi Hyun-woo,Naver / Line Webtoon,2012,Digital Webtoon,Full Color / Limited Palette,Historical / Romance,South Korea / Japan,3710,8.0,Ongoing,Korean,Teen+,NaN,13

In [16]:
comic_book_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   comic_id             10000 non-null  str
 1   Title                10000 non-null  str
 2   Writer               10000 non-null  str
 3   Artist               10000 non-null  str
 4   Studio/Publisher     10000 non-null  str
 5   Release Year         10000 non-null  int64
 6   Format               10000 non-null  str
 7   Theme (Color Style)  10000 non-null  str
 8   Genre                10000 non-null  str
 9   Country of Origin    10000 non-null  str
 10  Page Count           10000 non-null  int64
 11  Rating (out of 10)   10000 non-null  float64
 12  Status               10000 non-null  str
 13  Language             10000 non-null  str
 14  Age Rating           10000 non-null  str
 15  Awards               3984 non-null   str
 16  Volume Count         10000 non-null  int64
dtypes: float64(1), int64(3), str(13)
memory usage: 1.3 MB

In [36]:
null_count_by_col = {col: int(np.count_nonzero(comic_book_df[col].isna())) for col in comic_book_df.columns}
logger.info(f"Dataset directory: {filename}, null count by column: {null_count_by_col} with {len(comic_book_df)} rows")